name: Build pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
        with:
          token: ${{ secrets.TOKEN }}
          submodules: true

      - name: Deploy website
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.62.2
          TARGET_REPO: ffermi/ffermi.github.io
          TOKEN: ${{ secrets.TOKEN }}
          HUGO_ARGS: "-D"
          CNAME: ffermi.it
